#!/bin/bash

# always
./remove > /dev/null

# pull any recent changes first
if [[ ! $1 == "--force" ]]; then
	exec ./.internal/gitsync $(basename $0) $@
fi

TARGET_DIR=$(awk '$1=="SGOINFRE"{print $2}' .config)

if [ ! -d "$TARGET_DIR" ]; then
	echo "sgoinfre not found, wtf??"
	exit 1
fi

for file in $(awk '$1=="SCRIPTS"{print $2}' .config)/*.sm; do
	if [ -f "$file" ]; then
		chmod 755 "$file"
		cp "$file" "$TARGET_DIR"
		echo "Copied: $file"
	fi
done

echo "All stallman files have been copied."