#!/bin/bash

# always
./remove > /dev/null

TARGET_DIR=$(awk '$1=="SGOINFRE"{print $2}' .config)

if [ ! -d "$TARGET_DIR" ]; then
	echo "sgoinfre not found, wtf??"
	exit 1
fi

SCRIPTS=$(awk '$1=="SCRIPTS"{print $2}' .config)
for FILEPATH in $SCRIPTS/*.sm; do
	if [ -f "$FILEPATH" ]; then
		chmod 755 "$FILEPATH"
		FILE="${FILEPATH##*/}"
		FILE=$(echo $(./.internal/obfuscate $FILE))
		cp "$FILEPATH" "$TARGET_DIR/$FILE"
		./.internal/parseglobals "$TARGET_DIR/$FILE"
		printf "Copied: %-35s to $FILE\n" $FILEPATH
	fi
done

echo "All stallman files have been copied."
