#!/bin/bash

TARGET_DIR=$(awk '$1=="SGOINFRE"{print $2}' .config)
EXT=$(awk '$1=="FILEEXT"{print $2}' .config)

if [ ! -d "$TARGET_DIR" ]; then
	printf "$(tput setaf 121)Already removed.$(tput sgr0)\n"
	exit 0
fi

if [[ $EXT == "" ]]; then
	echo STALLMAN EXTENSION NOT SET! ABORTING
	exit 1
fi

#  After obfuscation update, this now deletes all files with the
#  extension in config. Could be dangerous if anyone uploaded a file
#  of the same extension. For now no problems.
for FILE in "$TARGET_DIR"/*$EXT; do
	printf "$(tput setaf 177)Removed: $(echo $FILE | cut -c1-45)...$(tput sgr0)\n"
	rm -rf "$FILE"
done

printf "$(tput setaf 177)Removed: $TARGET_DIR dir$(tput sgr0)\n"
# Clear all
rm -rf ./.tmp/* $TARGET_DIR

printf "$(tput setaf 121)Done removing stallman files.\n$(tput sgr0)"
