#!/bin/bash

TARGET_DIR=$(awk '$1=="SGOINFRE"{print $2}' .config)
EXT=$(awk '$1=="FILEEXT"{print $2}' .config)

if [ ! -d "$TARGET_DIR" ]; then
	printf "$(tput setaf 121)Already removed.$(tput sgr0)\n"
	exit 0
fi

if [[ $EXT == "" ]]; then
	echo STALLMAN EXTENSION NOT SET! ABORTING
	exit 1
fi

# Script folder is now pushed completely so there should be no problems with deleting other peoples .sm files
for DIR in /sgoinfre/*; do
	if [[ -d $DIR ]]; then
		if [[ ! $(ls $DIR | grep "$EXT") == "" ]]; then
			printf "$(tput setaf 177)Removed: from $TARGET_DIR directory$(tput sgr0)\n"
			rm -rf "$DIR/*$EXT"
		fi
	fi
done
# Nvm
for FILE in /sgoinfre/*$EXT; do
	printf "$(tput setaf 177)Removed: $(echo $FILE | cut -c1-45)...$(tput sgr0)\n"
	rm -rf "$FILE"
done

# Clear all
rm -rf ./.tmp/* $TARGET_DIR

printf "$(tput setaf 121)Done removing stallman files.\n$(tput sgr0)"
