#!/bin/bash

# This script only pulls once because if, for example, the file extension of the
# script changed after pulling; the script wouldnt remove the files with the old extension.

# pull any recent changes first
# if [[ ! $1 == "--force" ]]; then
# 	exec ./.internal/gitsync $(basename $0) $@
# fi

echo "Pushing for $1 seconds."

./push --force

count=$1
(( ++count ))
while (( --count >= 0 )); do
  printf "\rTime left: $count\033[0K"
  sleep 1
done
printf "\n"

./remove

echo "Time over, files removed."
