#!/bin/bash

echo "Pushing for $1 seconds."

./push --force

count=$1
(( ++count ))
while (( --count >= 0 )); do
  printf "\rTime left: $count\033[0K"
  sleep 1
done
printf "\n"

./remove

echo "Time over, files removed."
