#!/bin/bash

FILE=$1
EXT=$(awk '$1=="FILEEXT"{print $2}' .config)
ENABLED=$(awk '$1=="ENCRYPT"{print $2}' .config)
PASSWORD=$(awk '$1=="ENCRYPTPASS"{print $2}' .config)

if [[ ! $ENABLED == "true" ]]; then
	echo "encryption skipped"
	exit 1
fi

# TEMP=$(echo "$FILE.tmp" | sed "s/${EXT}//" )
# mv $FILE $TEMP
# ENCRYPTED=$(
openssl aes-128-cbc -iter 1000 -pass pass:'${PASSWORD}' < ${FILE} > ${FILE}
# )
# rm -rf $TEMP
