#!/bin/bash

#  This script ensures your repo is updated BEFORE running any command which pushes to sgoinfre.
CMD=$1
git fetch origin master
git stash push --include-untracked
git reset --hard origin master
git stash drop
git pull origin master
shift
./$CMD --force $@