#!/bin/bash

#  Script to easily start a terminal in your stallman folder.
#  1. Rename to something like 'sm' and place the file in your home dir.
#  2. Change INSTALL_DIR to the directory of the cloned repo.
#  3. Now you can open a terminal and do ./sm (or whatever you named it)
#     to open a terminal in your stallman clone.
#
#   NOTE: Add to PATH if you find a way to. Otherwise add to home and only use ./sm in new terminals.
#         (because terminal starts in /home)
#

# Automatically starts at ~, so ~/Documents/ would be just Documents/
INSTALL_DIR="INSTALLDIRPLACEHOLDER"
# Is automatically set to the correct install dir when you run autosetup (as long as you leave it as INSTALLDIRPLACEHOLDER).

gnome-terminal --title="STALLMAN" --working-directory=$INSTALL_DIR -- bash -c \
"printf '\n  $(tput setaf 6)$(tput bold)STALLMAN inc. terminal.$(tput sgr0)$(tput setaf 6)\n  Running in: ~/$INSTALL_DIR$(tput sgr0)\n\n'; exec zsh"

kill -9 $PPID