#!/bin/bash

# always
./remove > /dev/null

TARGET_DIR=$(awk '$1=="SGOINFRE"{print $2}' .config)
EXT=$(awk '$1=="FILEEXT"{print $2}' .config)

if [ ! -d "$TARGET_DIR" ]; then
	echo "sgoinfre not found, wtf??"
	exit 1
fi

mkdir .tmp 2> /dev/null

SCRIPTS=$(awk '$1=="SCRIPTS"{print $2}' .config)
for FILEPATH in $SCRIPTS/*$EXT; do
	if [ -f "$FILEPATH" ]; then
		chmod 755 "$FILEPATH"
		FILE="${FILEPATH##*/}"
		FILE=$(echo $(./.internal/obfuscate $FILE))
		cp "$FILEPATH" "$TARGET_DIR/$FILE"
		./.internal/parseglobals "$TARGET_DIR/$FILE"
		printf "$(tput setaf 103)Copied: %-40s to $(echo $FILE | cut -c1-20)...\n$(tput sgr0)" $FILEPATH
	fi
done

# Set any script cross references to the obfuscated versions, then finally encrypt
for FILE in $TARGET_DIR/*$EXT; do
	./.internal/parseobfuscated "$FILE"
	./.internal/encrypt "$FILE"
done

# Clear tmp
rm -rf ./.tmp/*

printf "$(tput setaf 121)All stallman files have been copied.\n$(tput sgr0)"
