#!/bin/bash

# Always
./remove > /dev/null

STALLMAN=$(awk '$1=="STALLMAN"{print $2}' .config)
TARGET_DIR=$(awk '$1=="SGOINFRE"{print $2}' .config)
EXT=$(awk '$1=="FILEEXT"{print $2}' .config)
OBFUSKEEP=$(awk '$1=="OBFUSKEEP"{print $2}' .config)
OBFUSCATE=$(awk '$1=="OBFUSCATE"{print $2}' .config)
ENCRYPTEXT=$(awk '$1=="ENCRYPTEXT"{print $2}' .config)
SCRIPTS=$(awk '$1=="SCRIPTS"{print $2}' .config)
PASSWORD=$(awk '$1=="ENCRYPTPASS"{print $2}' .config)

if [[ $OBFUSCATE == "true" ]]; then
	START=$(basename $TARGET_DIR | head -c5)
	OUT=$START$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c $((25)))
	TARGET_DIR="/sgoinfre/$OUT"
fi

if [ ! -d "$TARGET_DIR" ]; then
	mkdir $TARGET_DIR
	chmod g+w $TARGET_DIR
fi

PASSED=$(echo -e "SCRIPTEXT $EXT 
ENCRYPTEXT $ENCRYPTEXT 
PASSWORD $PASSWORD 
TARGET $TARGET_DIR")

for FILEPATH in $SCRIPTS/*$EXT; do
	if [ -f "$FILEPATH" ]; then
		chmod 755 "$FILEPATH"
		FILE="${FILEPATH##*/}"
		FILE=$(echo $(./.internal/obfuscate $FILE))
		cp "$FILEPATH" "$TARGET_DIR/$FILE"
		./.internal/parseglobals "$TARGET_DIR/$FILE"
		printf "$(tput setaf 103)Copied: %-25s to $(echo $FILE | cut -c1-20)...\n$(tput sgr0)" $(basename $FILEPATH)
	fi
done
printf "$(tput setaf 177)Releasing the STALLMAN...\n$(tput sgr0)" $(basename $FILEPATH)
sleep 0.25
STL="/sgoinfre/$(echo $(./.internal/obfuscate $(basename $STALLMAN)))"
cp $STALLMAN $STL
while read PAIR; do
	ENTRY=$(echo $PAIR | awk '{print $1}')
	# Get value from lookup
	VALUE=$(echo $PAIR | awk -v entry="$ENTRY" '$1==entry{print $2}')
	# Replace special globals
	sed -i "s,~$ENTRY~,$VALUE," $STL
	printf "$(tput setaf 103)Parsed: $ENTRY...\n"
done <<< $PASSED
sleep 0.3

# Encrypt
for FILE in $TARGET_DIR/*$EXT; do
	./.internal/encrypt "$FILE"
	printf "$(tput setaf 103)Encrypted: $(basename $FILE | cut -c1-46)...\n"
done

printf "$(tput setaf 121)STALLMAN is ready. Prefix: /sgoinfre/$(echo STALLMAN | cut -c1-$OBFUSKEEP) (tab)\n$(tput sgr0)"
