#!/bin/bash

# THE STALLMAN
PASSWORD=$(awk '$1=="ENCRYPTPASS"{print $2}' .config)

# This makes sure to reset brightness when terminal is closed
set () { xrandr --output eDP --brightness $1; }
quit () { set 1; }
trap quit EXIT

# SCRIPTS=./scripts
SCRIPTS=/sgoinfre/ST_test
SCRIPT="$SCRIPTS/$(cd $SCRIPTS && ls -d $1* | head -n1)"
echo $SCRIPT
openssl aes-128-cbc -iter 1000 -pass pass:$PASSWORD -d < $SCRIPT > $SCRIPT # Currently gives bad decrypt
echo $SCRIPT, $SCRIPTS, $1 > /home/owyciszk/Downloads/log.txt

# Full untracability protection
function _scriptalivedetector ()
{
	while true; do
		if ! ps -p $SCRPID > /dev/null; then
			kill -9 $1 > /dev/null
			kill -9 $2 > /dev/null
			exit 0
		fi
		sleep 0.2
	done
}
function _sysmondetector ()
{
	while true; do
		if [[ ! $(ps aux | grep -v "grep" | grep "gnome-system-monitor") == "" ]]; then
			kill -9 $1 > /dev/null
			kill -9 $2 > /dev/null
			kill -9 $3 > /dev/null
			exit 0
		fi
		sleep 0.2
	done
}
if [[ ! $1 == "nozsh" ]]; then
	# $SCRIPT &
	# SCRPID=$!
	history -p
	# clear
	# _scriptalivedetector $PPID $$ &
	# _sysmondetector $PPID $$ $SCRPID &
	# zsh
	# kill -9 $PPID > /dev/null
	# exit 0
fi
# _sysmondetector $$ &
