#!/bin/bash

#  This script ensures your repo is updated BEFORE running anything important.
CMD=$1
if [[ ! $(awk '$1=="DEBUG"{print $2}' .config) == "true" ]]; then
	git pull
fi
shift
./$CMD --force $@
