#!/bin/bash

# As of the obfuscation update, this file changes any of filenames present
# in scripts to their obfuscated counterparts.

FILE=$1
if [ -a ./.tmp/obfuscationtable ]; then
	awk '{print $1}' ./.tmp/obfuscationtable | while IFS= read -r ENTRY; do
		# Get value from .config
		VALUE=$(awk -v entry="$ENTRY" '$1==entry{print $2}' ./.tmp/obfuscationtable)

		# Replace globals
		sed -i "s,$ENTRY,$VALUE," $FILE
	done
fi
